### ISSUE TITLE
Better handling of empty lines

### ISSUE THREAD

**Issue by stefek99** [Shraymonks/code-jam#1]
Here: https://code.google.com/codejam/contest/351101/dashboard#s=p2

Input:

```
100

yes
no
foo bar
hello world
```

`readInt` uses `readWord` that in turn eats the line containing a space.

**Comment by stefek99** [comment]
Potential solution in line 26:

Replace `var T = input.readInt();`

With `var T = parseInt(input.readLine(), 10);`

Pull request that or maybe there is a better way?

**Comment by Shraymonks** [comment]
Nice catch! Yeah I think that's the best way to approach this right now. Feel free to make a PR!

Maybe in the future I'll add in an option for `readWord` to only read until a newline if that use case ever comes up.

**Comment by stefek99** [comment]
Yeah!

https://github.com/stefek99/Code-Jam/pull/1

**Comment by Shraymonks** [comment]
Can you create the PR for this repo? Then I can merge it!

**Comment by stefek99** [comment]
Ouch! Accidentally created PR for the mine repo...

Before we do this though --- see this example --- https://code.google.com/codejam/contest/90101/dashboard#s=p0

`The first line of input contains 3 integers, L, D and N separated by a space.`

**Comment by Shraymonks** [comment]
I'm think I'm okay with not supporting this. Since 2011 they have been consistent with having the first line of input being the number of test cases (`T`). This can be revisited if that changes in the future.

**Comment by stefek99** [comment]
Cool.

**Comment by Shraymonks** [comment]
Fixed the original case in 134f376f0b91917bd7e12a291fa0b8c333794db8
